services:
- type: web
  name: libraby-system
  runtime: node
  plan: free
  buildCommand: npm install && npm run build
  startCommand: npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 10000
